[versions]
spring-boot = "4.0.6"
spotless = "8.4.0"
spring-dependency-management = "1.1.7"
springdoc = "3.0.2"
mysql-connector = "9.7.0"
postgresql = "42.7.11"
mongodb-driver = "5.6.5"
bucket4j = "8.10.1"

[libraries]
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-quartz = { module = "org.springframework.boot:spring-boot-starter-quartz" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator-test = { module = "org.springframework.boot:spring-boot-starter-actuator-test" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-quartz-test = { module = "org.springframework.boot:spring-boot-starter-quartz-test" }
spring-boot-starter-validation-test = { module = "org.springframework.boot:spring-boot-starter-validation-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
lombok = { module = "org.projectlombok:lombok" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb-driver" }
bucket4j-core = { group = "com.bucket4j", name = "bucket4j-core", version.ref = "bucket4j" }
hibernate-community-dialects = { module = "org.hibernate.orm:hibernate-community-dialects" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
